"""Simple Streamlit frontend for demo"""
import streamlit as st
import requests
import json

st.set_page_config(
    page_title="AI Research Engine",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for a professional "Research" look
st.markdown("""
    <style>
    .main {
        background-color: #0e1117;
    }
    .stTextArea textarea {
        background-color: #1a1c24;
        color: #e0e0e0;
        border: 1px solid #3e4451;
    }
    .research-card {
        background-color: #161b22;
        padding: 2rem;
        border-radius: 12px;
        border: 1px solid #30363d;
        margin-bottom: 2rem;
    }
    .source-tag {
        display: inline-block;
        padding: 0.2rem 0.6rem;
        background-color: #238636;
        color: white;
        border-radius: 20px;
        font-size: 0.75rem;
        margin-right: 0.5rem;
        margin-bottom: 0.5rem;
        text-decoration: none;
    }
    .source-tag:hover {
        background-color: #2ea043;
        color: white;
    }
    h1, h2, h3 {
        color: #58a6ff !important;
    }
    </style>
    """, unsafe_allow_html=True)

st.title("🔬 AI Research Engine")
st.markdown("*Advanced Intelligence for Deep Retrieval and Structured Reporting*")

# API configuration
API_URL = st.sidebar.text_input(
    "API URL",
    value="http://localhost:8000",
    help="Cloud Run URL or localhost for testing"
)

PROVIDER = st.sidebar.selectbox(
    "LLM Provider",
    options=["groq", "openai", "anthropic"],
    index=0
)

# Session state
if 'session_id' not in st.session_state:
    st.session_state.session_id = None

if 'history' not in st.session_state:
    st.session_state.history = []

# Query input
query = st.text_area(
    "Enter your research question:",
    height=100,
    placeholder="e.g., What are the latest advancements in LangGraph?"
)

col1, col2 = st.columns([1, 5])
with col1:
    search_button = st.button("🔍 Research", type="primary")
with col2:
    clear_button = st.button("🗑️ Clear History")

if clear_button:
    st.session_state.history = []
    st.session_state.session_id = None
    st.rerun()

if search_button and query:
    with st.spinner("Researching..."):
        try:
            response = requests.post(
                f"{API_URL}/research",
                json={
                    "query": query,
                    "session_id": st.session_state.session_id,
                    "provider": PROVIDER
                },
                timeout=90
            )
            
            if response.status_code == 200:
                data = response.json()
                st.session_state.session_id = data.get('session_id')
                
                # Add to history
                st.session_state.history.append({
                    "query": query,
                    "response": data.get('answer'),
                    "sources": data.get('sources', []),
                    "provider": data.get('provider')
                })
                
                st.success("Research complete!")
            else:
                st.error(f"Error: {response.text}")
                
        except Exception as e:
            st.error(f"Request failed: {e}")

# Display history
if st.session_state.history:
    st.markdown("---")
    st.subheader("📑 Research Reports")
    
    for i, item in enumerate(reversed(st.session_state.history)):
        provider_name = item.get('provider', 'AI').upper()
        with st.container():
            st.markdown(f"### [Report] {item['query']}")
            st.info(f"Generated by: **{provider_name}**")
            
            # Response in a nice card
            st.markdown('<div class="research-card">', unsafe_allow_html=True)
            st.markdown(item['response'])
            st.markdown('</div>', unsafe_allow_html=True)
            
            # Sources as tags
            if item['sources']:
                st.markdown("#### 🔗 Referenced Sources")
                cols = st.columns(len(item['sources']) if len(item['sources']) < 5 else 5)
                for idx, source in enumerate(item['sources']):
                    with cols[idx % 5]:
                        st.markdown(f"[{source.get('title', 'Source')[:20]}...]({source.get('url', '#')})")
            
            st.divider()
